apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: cockroachdb-system
  annotations:
    reconcile.fluxcd.io/requestedAt: "string-to-be-replaced-by-flux" 
spec:
  template:
    spec:
      containers:
      - name: prisma
        image: node:latest
        command: 
          - "sh"
          - "-c"
          - |
            cd /prisma && \
            npx prisma@5.22.0 db push --accept-data-loss --skip-generate && \
            node -e "
            const { Client } = require('pg');
            async function run() {
              const client = new Client(process.env.DATABASE_URL);
              await client.connect();
              // Extra idempotent unsupported SQL commands here.
              await client.query('ALTER TABLE \"User\" SET LOCALITY REGIONAL BY ROW;');
              await client.query('ALTER TABLE \"Talent\" SET LOCALITY REGIONAL BY ROW;');
              console.log('Applied CockroachDB itempotent commands unsupported by prisma.');
              await client.end();
            }
            run();
            "
        env:
        - name: DATABASE_URL
          value: "postgresql://root@cockroachdb-public.cockroachdb-system:26257/defaultdb?sslmode=disable"
        volumeMounts:
        - name: schema-volume
          mountPath: /prisma
      volumes:
      - name: schema-volume
        configMap:
          name: prisma-schema-files
      restartPolicy: OnFailure
