name: Go Project CI
on:
  push:
    paths:
      - 'go/**'

jobs:
  bazel-build:
    runs-on: bazel-heavy
    steps:
      - name: Manual Clone
        run: |
          git clone http://x-access-token:${{ secrets.GITHUB_TOKEN }}@forgejo-http.forgejo:3000/${{ github.repository }}.git .
      
      - name: Bazel Version
        run: |
          bazel build //go/examples/helloword
