name: Global Runtime Config
on:
  push:
    branches:
      - 'main'

jobs:
  update-redis:
    runs-on: bazel-heavy
    steps:
      - uses: actions/checkout@v4
      - name: Bazel Version
        run: |
          bazel version
