name: Administrative Ops
on:
  push:
    branches:
      - 'sudo'

jobs:
  cluster-management:
    runs-on: k8s-admin
    steps:
      - name: Manual Clone
        run: |
          git clone http://x-access-token:${{ secrets.GITHUB_TOKEN }}@forgejo-http.forgejo:3000/${{ github.repository }}.git .
      - name: Apply Cluster Changes
        run: |
          kubectl apply -f cluster/namespaces/
          kubectl apply -f cluster/monitoring/
          echo "Cluster state updated via sudo branch."
