name: Native Checkout
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: bazel-heavy
    steps:
      - name: Manual Clone
        run: |
          # Use the internal Forgejo URL and the automatic token
          # This assumes your FORGEJO_URL is accessible from within the pod
          git clone http://x-access-token:${{ secrets.GITHUB_TOKEN }}@forgejo-http.forgejo:3000/${{ github.repository }}.git .
         
          
      - name: Verify Bazel
        run: |
          bazel version
