apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cockroachdb
  namespace: cockroachdb-system
spec:
  nodes: 3
  image:
    name: cockroachdb/cockroach:v24.1.0 # Use the latest stable version
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 10Gi
  resources:
    requests:
      cpu: 0.1
      memory: 4Gi
