apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - replicator
  - bazel-runner
  #- cockroach
  - dashboards
  - grafana
  - minio
  - nativelink
  #- prisma
  #- spark
  - tofu-controller
  - users
  - zot

