apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bazel-runner
  namespace: flux-system
spec:
  serviceName: "bazel-runner"
  replicas: 3
  selector:
    matchLabels:
      app: bazel-runner
  template:
    metadata:
      labels:
        app: bazel-runner
    spec:
      serviceAccountName: gitea-runner-admin
      hostAliases:
      - ip: "10.43.173.111"
        hostnames:
        - "git.example.com"
      initContainers:
      - name: install-runner
        image: gitea/act_runner:latest
        command: ["cp", "/usr/local/bin/act_runner", "/shared/act_runner"]
        volumeMounts:
        - name: shared-vol
          mountPath: /shared
      containers:
      - name: bazel-runtime
        image: pizzafactory0contorno/bazelisk:ubuntu-22.04
        env:
        - name: FORGEJO_URL
          value: "http://forgejo-http.forgejo:3000"
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: forgejo-admin-token
              key: RUNNER_REGISTRATION_TOKEN
        resources:
          requests:
            cpu: 500m
            memory: 4Gi
            ephemeral-storage: 1Gi
          limits:
            cpu: 2
            memory: 8Gi
            ephemeral-storage: 10Gi
        command: ["/bin/sh", "-c"]
        args:
          - |
            /shared/act_runner register \
              --instance "$FORGEJO_URL" \
              --token "$GITEA_RUNNER_REGISTRATION_TOKEN" \
              --name "$(hostname)" \
              --labels "bazel-heavy:host,k8s-admin:host" \
              --no-interactive;
            
            # Optimize clone
            REPO_DIR="/data/my-org/cloned-repo"
            REPO_URL="http://forgejo-http.forgejo:3000/my-org/cloned-repo.git"
            
            mkdir -p "/data/my-org"
            if [ ! -d "$REPO_DIR/.git" ]; then
              echo "Cloning repo..."
              git clone "$REPO_URL" "$REPO_DIR"
            else
              echo "Fetching repo..."
              cd "$REPO_DIR"
              git fetch
              git checkout main
            fi
            
            /shared/act_runner daemon
        lifecycle:
          preStop:
            exec:
              command: ["/shared/act_runner", "unregister"]
        volumeMounts:
        - name: shared-vol
          mountPath: /shared
        - name: work-dir
          mountPath: /data
      volumes:
      - name: shared-vol
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: work-dir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
