apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazel-runner
  namespace: flux-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bazel-runner
  template:
    metadata:
      labels:
        app: bazel-runner
    spec:
      serviceAccountName: gitea-runner-admin
      hostAliases:
      - ip: "10.43.173.111"
        hostnames:
        - "git.example.com"
      initContainers:
      - name: install-runner
        image: gitea/act_runner:latest
        command: ["cp", "/usr/local/bin/act_runner", "/shared/act_runner"]
        volumeMounts:
        - name: shared-vol
          mountPath: /shared
      containers:
      - name: bazel-runtime
        image: pizzafactory0contorno/bazelisk:ubuntu-22.04
        env:
        - name: FORGEJO_URL
          value: "http://forgejo-http.forgejo:3000"
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: forgejo-admin-token
              key: RUNNER_REGISTRATION_TOKEN
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
            ephemeral-storage: 1Gi
          limits:
            cpu: 2
            memory: 4Gi
            ephemeral-storage: 10Gi
        command: ["/bin/sh", "-c"]
        args:
          - |
            /shared/act_runner register \
              --instance "$FORGEJO_URL" \
              --token "$GITEA_RUNNER_REGISTRATION_TOKEN" \
              --name "$(hostname)" \
              --labels "bazel-heavy:host,k8s-admin:host" \
              --no-interactive;
            /shared/act_runner daemon
        lifecycle:
          preStop:
            exec:
              command: ["/shared/act_runner", "unregister"]
        volumeMounts:
        - name: shared-vol
          mountPath: /shared
        - name: work-dir
          mountPath: /data
      volumes:
      - name: shared-vol
        emptyDir: {}
      - name: work-dir
        emptyDir: {}
