apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: gitea-resources
  namespace: forgejo
spec:
  interval: 5m
  approvePlan: "auto"
  path: ./terraform
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  varsFrom:
    - kind: Secret
      name: forgejo-admin
    - kind: Secret
      name: gitea-flux-password
  writeOutputsToSecret:
    name: forgejo-admin-token
