apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitea-terraform.yaml
  - minio.yaml
  - spark-hello-world.yaml
  - users-terraform.yaml
  - lgtm-stack.yaml
  - custom-dashboard-sample.yaml
  - bazel-runner.yaml
  - bazel-runner-sa.yaml

