apiVersion: v1
kind: Namespace
metadata:
  name: nativelink
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nativelink
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://public.ecr.aws/b1l4l6w7/tracemachina
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nativelink
  namespace: nativelink
spec:
  releaseName: nativelink
  chart:
    spec:
      chart: nativelink
      version: 1.0.0-rc1
      sourceRef:
        kind: HelmRepository
        name: nativelink
        namespace: flux-system
  interval: 1h
  values:
    cas:
      enabled: true
      cloudProvider: "filesystem"
      persistentVolume:
        enabled: true
        size: 20Gi
    rbe:
      enabled: true
    workers:
      enabled: true
      specs:
      - name: worker-1
        replicas: 1
        podImage: "l.gcr.io/google/bazel:latest"
        platformProperties:
          osFamily: "Linux"
          ISA: "x86-64"
    redis:
      enabled: true
      sentinel:
        enabled: true
        image:
          repository: bitnami/redis-sentinel
          tag: 7.2.4-debian-12-r10
      metrics:
        enabled: true
        image:
          repository: bitnami/redis-exporter
          tag: 1.58.0-debian-12-r8
    # workerProvisioner seems to be able to do auto-scaling. Slick!
