apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- switchover.yaml
- gitea-helmrelease.yaml
- ../../../bootstrap/tf-controller-install.yaml
- apps-kustomization.yaml
- spark-operator.yaml
- cockroach-operator-kustomization.yaml
- cockroach-cluster-kustomization.yaml
- cockroach-operator-gitrepo.yaml

