apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-app-schema
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/my-cluster/apps/myapp
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  dependsOn:
    - name: cockroach-cluster
    - name: atlas-operator
