apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.admission.config.k8s.io/enforce: privileged
    pod-security.admission.config.k8s.io/enforce-version: latest
    pod-security.admission.config.k8s.io/audit: privileged
    pod-security.admission.config.k8s.io/audit-version: latest
    pod-security.admission.config.k8s.io/warn: privileged
    pod-security.admission.config.k8s.io/warn-version: latest
