apiVersion: v1
kind: Secret
metadata:
  name: atlas-db-credentials
  namespace: cockroachdb-system
stringData:
  url: "postgres://root@cockroachdb-public.cockroachdb-system:26257/myapp?sslmode=disable"
  dev_url: "postgres://root@cockroachdb-public.cockroachdb-system:26257/atlas_dev?sslmode=disable"
